//Work with API
export const LOAD_SHEDULE_FROM_API = "LOAD_SHEDULE_FROM_API";
export const LOAD_GROUPS_FROM_API = "LOAD_GROUPS_FROM_API";
export const LOAD_TEACHERS_FROM_API = "LOAD_TEACHERS_FROM_API";
export const LOAD_DATA_FOR_SEARCH_FROM_API = "LOAD_DATA_FOR_SEARCH_FROM_API";
export const USER_DATA_LOAD_FROM_API = "USER_DATA_LOAD_FROM_API";
//Work inside client
export const SET_SHEDULE = "SET_SHEDULE";
export const SET_GROUPS = "SET_GROUPS";
export const SEARCHED_GROUP_SELECTED = "SEARCHED_GROUP_SELECTED";
export const CLEAR_GROUP_SELECTED = "CLEAR_GROUP_SELECTED";

export const SET_ENTERED_GROUP = "SET_ENTERED_GROUP";
export const SHOW_FILTERED_GROUPS = "SHOW_FILTERED_GROUPS";

export const SET_DISCIPLINES = "SET_DISCIPLINES";
export const SET_DISCIPLINES_DATA = "SET_DISCIPLINES";
export const SET_DATA_FOR_SEARCH = "SET_DATA_FOR_SEARCH";
export const SET_TEACHERS = "SET_TEACHERS";
export const SET_ENTERED_TEACHER = "SET_ENTERED_TEACHER";
export const SHOW_FILTERED_TEACHERS = "SHOW_FILTERED_TEACHERS";
export const CLEAR_TEACHER_SELECTED = "CLEAR_TEACHER_SELECTED";
export const SEARCHED_TEACHER_SELECTED = "SEARCHED_TEACHER_SELECTED";

//admin types
export const LOGIN_IS_CLICKED = "LOGIN_IS_CLICKED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_END = "LOGIN_END";
export const ADMIN_IS_LOADING = "ADMIN_IS_LOADING";
export const SET_ADMIN_DATA = "SET_ADMIN_DATA";
export const CREATE_NEW_DATA = "CREATE_NEW_DATA";
export const DELETE_FROM_API = "DELETE_FROM_API";
export const UPDATE_ADMIN_GROUP = "UPDATE_ADMIN_GROUP";
export const UPDATE_ADMIN_OBJECTS = "UPDATE_ADMIN_OBJECTS";
export const UPDATE_ADMIN_TEACHERS = "UPDATE_ADMIN_TEACHERS";
export const UPDATE_ADMIN_SPECIALTIES = "UPDATE_ADMIN_SPECIALTIES";
export const UPDATE_ADMIN_FACULTY = "UPDATE_ADMIN_FACULTY";
export const UPDATE_ADMIN_ROOMS = "UPDATE_ADMIN_ROOMS";
export const UPDATE_ADMIN_BUILDINGS = "UPDATE_ADMIN_BUILDINGS";
export const EDIT_OPERATION_API = "EDIT_OPERATION_API";
export const SEARCHED_DAY_SELECTED = "SEARCHED_DAY_SELECTED";
//workflow
export const SET_DATA_FLOW = "SET_DATA_FLOW";
export const UPDATE_SHEDULE_IN_BD = "UPDATE_SHEDULE_IN_BD";
export const NEW_TABLE_IN_BD = "NEW_TABLE_IN_BD";
